#!/usr/bin/env tsx

/**
 * Simple compilation helper for SimpleEscrowUSDC contract
 * Uses the solc compiler to generate bytecode and ABI
 * 
 * Usage: npx tsx scripts/compile-usdc-escrow.ts
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';

const execAsync = promisify(exec);

async function compileContract() {
  console.log('🔨 Compiling SimpleEscrowUSDC contract...');
  
  const contractPath = path.join(process.cwd(), 'src/blockchain/SimpleEscrowUSDC.sol');
  
  if (!fs.existsSync(contractPath)) {
    console.error('❌ Contract file not found:', contractPath);
    process.exit(1);
  }
  
  try {
    // Check if solc is installed
    console.log('🔍 Checking for solc compiler...');
    await execAsync('solc --version');
    
    // Compile the contract
    console.log('⚙️ Compiling contract...');
    const { stdout } = await execAsync(`solc --bin --abi --optimize "${contractPath}"`);
    
    // Parse output to extract bytecode and ABI
    const lines = stdout.split('\n');
    let bytecode = '';
    let abi = '';
    let capturing = '';
    
    for (const line of lines) {
      if (line.includes('Binary:')) {
        capturing = 'bytecode';
        continue;
      } else if (line.includes('Contract JSON ABI')) {
        capturing = 'abi';
        continue;
      } else if (line.includes('======')) {
        capturing = '';
        continue;
      }
      
      if (capturing === 'bytecode' && line.trim()) {
        bytecode = line.trim();
      } else if (capturing === 'abi' && line.trim()) {
        abi = line.trim();
      }
    }
    
    if (!bytecode || !abi) {
      throw new Error('Failed to extract bytecode or ABI from compilation output');
    }
    
    // Save compilation artifacts
    const artifactPath = path.join(process.cwd(), 'src/blockchain/SimpleEscrowUSDC_compiled.json');
    const artifact = {
      contractName: 'SimpleEscrowUSDC',
      abi: JSON.parse(abi),
      bytecode: '0x' + bytecode,
      compiler: 'solc',
      compiledAt: new Date().toISOString(),
    };
    
    fs.writeFileSync(artifactPath, JSON.stringify(artifact, null, 2));
    
    console.log('✅ Contract compiled successfully!');
    console.log('📁 Artifact saved to:', artifactPath);
    console.log('📏 Bytecode length:', bytecode.length, 'characters');
    console.log('🔧 ABI functions:', artifact.abi.filter((item: any) => item.type === 'function').length);
    console.log('📢 Events:', artifact.abi.filter((item: any) => item.type === 'event').length);
    
    // Show next steps
    console.log('\n🎯 Next steps:');
    console.log('1. Review the compiled artifact at:', artifactPath);
    console.log('2. Update deploy-usdc-escrow.ts to use the generated bytecode');
    console.log('3. Run deployment: npx tsx scripts/deploy-usdc-escrow.ts');
    
  } catch (error) {
    console.error('❌ Compilation failed:', error);
    
    if (error instanceof Error && error.message.includes('solc: command not found')) {
      console.log('\n💡 Install solc compiler:');
      console.log('npm install -g solc');
      console.log('or use yarn: yarn global add solc');
    }
    
    process.exit(1);
  }
}

compileContract().catch(console.error);